---
deployment:
  tasks:
    - /bin/cp -f index.html $HOME/keepenviro.ro/
    - /bin/cp -f .htaccess $HOME/keepenviro.ro/
    - /bin/cp -Rf css $HOME/keepenviro.ro/
    - /bin/cp -Rf js $HOME/keepenviro.ro/
